apiVersion: v1
kind: Service
metadata:
  name: pgweb-lb
spec:
  selector:
    app: pgweb
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
spec:
  selector:
    matchLabels:
      app: pgweb
  replicas: 1
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
      - name: pgweb
        image: sosedoff/pgweb
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: "postgres://demouser:demopasswd@cockroachdb-public:26257/defaultdb"
        ports:
        - containerPort: 8081
      restartPolicy: Always

